import type { Command, AgentContext } from '../interface.js';

export const helpCommand: Command = {
  definition: {
    name: 'help',
    description: 'List all available commands',
    source: 'builtin',
  },
  async execute(_args: Record<string, string>, _context: AgentContext): Promise<void> {
    // Actual help output is generated by the registry at execution time
    // This is a placeholder — the registry overrides this in practice
    console.log('Type /commands to list all available commands.');
  },
};
