import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { ttyPrompt } from '../cli/tty-prompt.js';
import { logger } from '../core/logger.js';

export interface GlobalInitResult {
  skipped: boolean;   // ~/.copair/ already existed
  declined: boolean;  // user said n
  created: boolean;   // scaffolded this run
}

const GLOBAL_CONFIG_TEMPLATE = `# Copair global configuration
# Generated by Copair on first run — edit as needed

# provider:
#   name: anthropic          # anthropic | openai | google | ollama
#   model: claude-sonnet-4-6
#   api_key: your-api-key-here
#   endpoint: ~              # optional override (e.g. for local Ollama)

# identity:
#   name: ~                  # used in git co-author trailers
#   email: ~

# ui:
#   status_bar: true
#   syntax_highlight: true
#   vi_mode: false
#   bordered_input: true

# permissions:
#   mode: ask                # ask | auto | deny

# context:
#   summarization_model: ~   # model used for session summarisation
#   max_sessions: 50
`;

export class GlobalInitManager {
  private globalDir: string;

  constructor(homeDir?: string) {
    this.globalDir = join(homeDir ?? homedir(), '.copair');
  }

  async check(options: { ci: boolean } = { ci: false }): Promise<GlobalInitResult> {
    if (existsSync(this.globalDir)) {
      return { skipped: true, declined: false, created: false };
    }

    // In CI mode, skip global scaffold — continue with built-in defaults
    if (options.ci) {
      return { skipped: false, declined: true, created: false };
    }

    const answer = ttyPrompt('Set up global Copair config at ~/.copair/? (Y/n) ');
    if (answer === null) {
      logger.info('init', 'TTY unavailable — treating as CI mode (deny)');
      return { skipped: false, declined: true, created: false };
    }
    const declined = answer === 'n' || answer === 'no';

    if (declined) {
      return { skipped: false, declined: true, created: false };
    }

    await this.scaffold();
    return { skipped: false, declined: false, created: true };
  }

  private async scaffold(): Promise<void> {
    mkdirSync(this.globalDir, { recursive: true, mode: 0o700 });
    const configPath = join(this.globalDir, 'config.yaml');
    if (!existsSync(configPath)) {
      writeFileSync(configPath, GLOBAL_CONFIG_TEMPLATE, { mode: 0o600 });
    }
  }
}
